/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.*;
import data.*;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author cda402
 */
public class OuvrageSwing extends javax.swing.JFrame {

    /**
     * Creates new form Ouvrage
     */
    private Librairie lib = new Librairie();

    public OuvrageSwing() {
        lib.load();
        Collections.sort(lib.getLesSous_themes());
        initComponents();
        this.pnl_cb_theme.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_theme_sous_theme = new javax.swing.ButtonGroup();
        javax.swing.JTabbedPane pnl_mots_cles = new javax.swing.JTabbedPane();
        pnl_ouvrages = new javax.swing.JPanel();
        pnl_themes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree_theme = new javax.swing.JTree();
        rb_theme = new javax.swing.JRadioButton();
        rb_sous_theme = new javax.swing.JRadioButton();
        pnl_cb_theme = new javax.swing.JPanel();
        lbl_cb_theme = new javax.swing.JLabel();
        cb_theme = new javax.swing.JComboBox();
        pnl_info_theme = new javax.swing.JPanel();
        lbl_theme_id_libelle = new javax.swing.JLabel();
        lbl_theme_id = new javax.swing.JLabel();
        lbl_libelle_theme_libelle = new javax.swing.JLabel();
        tf_theme_libelle = new javax.swing.JTextField();
        btn_theme_ajouter = new javax.swing.JButton();
        btn_theme_modifier = new javax.swing.JButton();
        btn_theme_afficher = new javax.swing.JButton();
        pnl_auteur_rechercher1 = new javax.swing.JPanel();
        tf_themes_recherche = new javax.swing.JTextField();
        btn_theme_recherche = new javax.swing.JButton();
        lbl_theme_rechercher = new javax.swing.JLabel();
        pnl_auteurs = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_auteur_id_libelle = new javax.swing.JLabel();
        lbl_auteur_nom_libelle = new javax.swing.JLabel();
        tf_auteur_nom = new javax.swing.JTextField();
        lbl_auteur_prenom_libelle = new javax.swing.JLabel();
        tf_auteur_prenom = new javax.swing.JTextField();
        lbl_auteur_naissance_libelle = new javax.swing.JLabel();
        tf_auteur_naissance = new javax.swing.JTextField();
        lbl_auteur_deces_libelle = new javax.swing.JLabel();
        tf_auteur_deces = new javax.swing.JTextField();
        btn_auteur_ajouter = new javax.swing.JButton();
        btn_auteur_modifier = new javax.swing.JButton();
        lbl_auteur_id = new javax.swing.JLabel();
        btn_auteurs_info_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_auteur = new javax.swing.JTree();
        btn_auteur_afficher = new javax.swing.JButton();
        pnl_auteur_rechercher = new javax.swing.JPanel();
        tf_auteurs_recherche = new javax.swing.JTextField();
        btn_auteur_recherche = new javax.swing.JButton();
        lbl_auteur_rechercher = new javax.swing.JLabel();
        pnl_editeurs = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree_editeurs = new javax.swing.JTree();
        pnl_info_editeur = new javax.swing.JPanel();
        pnl_evenement = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree_Evenement = new javax.swing.JTree();
        pnl_info_evenement = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnl_ouvragesLayout = new javax.swing.GroupLayout(pnl_ouvrages);
        pnl_ouvrages.setLayout(pnl_ouvragesLayout);
        pnl_ouvragesLayout.setHorizontalGroup(
            pnl_ouvragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        pnl_ouvragesLayout.setVerticalGroup(
            pnl_ouvragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        pnl_mots_cles.addTab("Ouvrages", pnl_ouvrages);

        jTree_theme.setModel(initThemesTreeModel());
        jScrollPane2.setViewportView(jTree_theme);

        btngrp_theme_sous_theme.add(rb_theme);
        rb_theme.setText("Thème");
        rb_theme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_themeItemStateChanged(evt);
            }
        });

        btngrp_theme_sous_theme.add(rb_sous_theme);
        rb_sous_theme.setText("Sous-thème");
        rb_sous_theme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_sous_themeItemStateChanged(evt);
            }
        });

        pnl_cb_theme.setBackground(new java.awt.Color(204, 255, 255));

        lbl_cb_theme.setText("Son Thème");

        cb_theme.setModel(initThemeModelComboBox());

        javax.swing.GroupLayout pnl_cb_themeLayout = new javax.swing.GroupLayout(pnl_cb_theme);
        pnl_cb_theme.setLayout(pnl_cb_themeLayout);
        pnl_cb_themeLayout.setHorizontalGroup(
            pnl_cb_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cb_themeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cb_theme, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb_theme, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_cb_themeLayout.setVerticalGroup(
            pnl_cb_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cb_themeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_cb_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cb_theme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_theme, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_info_theme.setBackground(new java.awt.Color(204, 255, 255));

        lbl_theme_id_libelle.setText("Identifiant :");

        lbl_theme_id.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lbl_theme_id.setForeground(new java.awt.Color(0, 102, 51));

        lbl_libelle_theme_libelle.setText("Libellé");

        javax.swing.GroupLayout pnl_info_themeLayout = new javax.swing.GroupLayout(pnl_info_theme);
        pnl_info_theme.setLayout(pnl_info_themeLayout);
        pnl_info_themeLayout.setHorizontalGroup(
            pnl_info_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_info_themeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl_info_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_libelle_theme_libelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_theme_id_libelle, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnl_info_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_theme_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_theme_libelle))
                .addContainerGap())
        );
        pnl_info_themeLayout.setVerticalGroup(
            pnl_info_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_info_themeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_info_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_theme_id_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_theme_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_info_themeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_libelle_theme_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_theme_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        btn_theme_ajouter.setBackground(new java.awt.Color(153, 255, 153));
        btn_theme_ajouter.setText("Ajouter");
        btn_theme_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_theme_ajouterActionPerformed(evt);
            }
        });

        btn_theme_modifier.setBackground(new java.awt.Color(255, 255, 153));
        btn_theme_modifier.setText("Modifier");
        btn_theme_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_theme_modifierActionPerformed(evt);
            }
        });

        btn_theme_afficher.setBackground(new java.awt.Color(153, 204, 255));
        btn_theme_afficher.setText("Afficher");
        btn_theme_afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_theme_afficherActionPerformed(evt);
            }
        });

        pnl_auteur_rechercher1.setBackground(new java.awt.Color(204, 255, 255));

        btn_theme_recherche.setText("ok");
        btn_theme_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_theme_rechercheActionPerformed(evt);
            }
        });

        lbl_theme_rechercher.setText("Rechercher");

        javax.swing.GroupLayout pnl_auteur_rechercher1Layout = new javax.swing.GroupLayout(pnl_auteur_rechercher1);
        pnl_auteur_rechercher1.setLayout(pnl_auteur_rechercher1Layout);
        pnl_auteur_rechercher1Layout.setHorizontalGroup(
            pnl_auteur_rechercher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_auteur_rechercher1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_theme_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_themes_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_theme_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnl_auteur_rechercher1Layout.setVerticalGroup(
            pnl_auteur_rechercher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_auteur_rechercher1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_auteur_rechercher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_theme_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_theme_recherche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_themes_recherche, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_themesLayout = new javax.swing.GroupLayout(pnl_themes);
        pnl_themes.setLayout(pnl_themesLayout);
        pnl_themesLayout.setHorizontalGroup(
            pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_themesLayout.createSequentialGroup()
                .addGroup(pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_themesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_theme_afficher, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_themesLayout.createSequentialGroup()
                        .addGroup(pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_themesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnl_info_theme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnl_cb_theme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnl_auteur_rechercher1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_themesLayout.createSequentialGroup()
                                        .addComponent(btn_theme_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_theme_modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(pnl_themesLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(rb_theme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb_sous_theme)
                                .addGap(83, 83, 83)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_themesLayout.setVerticalGroup(
            pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_themesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_themesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnl_themesLayout.createSequentialGroup()
                        .addComponent(pnl_auteur_rechercher1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_sous_theme)
                            .addComponent(rb_theme))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_info_theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_cb_theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_theme_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_theme_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)))
                .addComponent(btn_theme_afficher, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnl_mots_cles.addTab("Thèmes & Sous-Thèmes", pnl_themes);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lbl_auteur_id_libelle.setText("Identifiant");

        lbl_auteur_nom_libelle.setText("Nom");

        lbl_auteur_prenom_libelle.setText("Prenom");

        lbl_auteur_naissance_libelle.setText("Date de naissance");

        lbl_auteur_deces_libelle.setText("Date de décès");

        btn_auteur_ajouter.setBackground(new java.awt.Color(204, 255, 204));
        btn_auteur_ajouter.setText("Ajouter");
        btn_auteur_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auteur_ajouterActionPerformed(evt);
            }
        });

        btn_auteur_modifier.setBackground(new java.awt.Color(255, 255, 204));
        btn_auteur_modifier.setText("Modifier");
        btn_auteur_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auteur_modifierActionPerformed(evt);
            }
        });

        btn_auteurs_info_reset.setBackground(new java.awt.Color(255, 153, 102));
        btn_auteurs_info_reset.setText("Reset");
        btn_auteurs_info_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auteurs_info_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_auteur_ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_auteur_deces_libelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_auteur_naissance_libelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(lbl_auteur_prenom_libelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_auteur_nom_libelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_auteur_id_libelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_auteur_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(tf_auteur_prenom)
                    .addComponent(tf_auteur_naissance)
                    .addComponent(tf_auteur_deces)
                    .addComponent(lbl_auteur_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_auteur_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_auteurs_info_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_auteur_id_libelle, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(lbl_auteur_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_auteur_nom_libelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_auteur_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_auteur_prenom_libelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_auteur_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_auteur_naissance_libelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_auteur_naissance, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_auteur_deces_libelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_auteur_deces, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_auteur_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_auteur_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_auteurs_info_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTree_auteur.setModel(initAuteursTreeModel());
        jScrollPane1.setViewportView(jTree_auteur);

        btn_auteur_afficher.setBackground(new java.awt.Color(102, 204, 255));
        btn_auteur_afficher.setText("Afficher");
        btn_auteur_afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auteur_afficherActionPerformed(evt);
            }
        });

        pnl_auteur_rechercher.setBackground(new java.awt.Color(204, 255, 255));

        btn_auteur_recherche.setText("ok");
        btn_auteur_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auteur_rechercheActionPerformed(evt);
            }
        });

        lbl_auteur_rechercher.setText("Rechercher");

        javax.swing.GroupLayout pnl_auteur_rechercherLayout = new javax.swing.GroupLayout(pnl_auteur_rechercher);
        pnl_auteur_rechercher.setLayout(pnl_auteur_rechercherLayout);
        pnl_auteur_rechercherLayout.setHorizontalGroup(
            pnl_auteur_rechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_auteur_rechercherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_auteur_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_auteurs_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_auteur_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_auteur_rechercherLayout.setVerticalGroup(
            pnl_auteur_rechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_auteur_rechercherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_auteur_rechercherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_auteur_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_auteur_recherche, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(tf_auteurs_recherche, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_auteursLayout = new javax.swing.GroupLayout(pnl_auteurs);
        pnl_auteurs.setLayout(pnl_auteursLayout);
        pnl_auteursLayout.setHorizontalGroup(
            pnl_auteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_auteursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_auteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_auteur_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_auteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(btn_auteur_afficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_auteursLayout.setVerticalGroup(
            pnl_auteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_auteursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_auteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_auteursLayout.createSequentialGroup()
                        .addComponent(pnl_auteur_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_auteursLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_auteur_afficher, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnl_mots_cles.addTab("Auteurs", pnl_auteurs);

        jTree_editeurs.setModel(initEditeursTreeModel());
        jScrollPane3.setViewportView(jTree_editeurs);

        pnl_info_editeur.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pnl_info_editeurLayout = new javax.swing.GroupLayout(pnl_info_editeur);
        pnl_info_editeur.setLayout(pnl_info_editeurLayout);
        pnl_info_editeurLayout.setHorizontalGroup(
            pnl_info_editeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        pnl_info_editeurLayout.setVerticalGroup(
            pnl_info_editeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_editeursLayout = new javax.swing.GroupLayout(pnl_editeurs);
        pnl_editeurs.setLayout(pnl_editeursLayout);
        pnl_editeursLayout.setHorizontalGroup(
            pnl_editeursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_editeursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_info_editeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_editeursLayout.setVerticalGroup(
            pnl_editeursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_editeursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_editeursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(pnl_info_editeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_mots_cles.addTab("Editeurs", pnl_editeurs);

        jTree_Evenement.setModel(initEvenementsTreeModel());
        jScrollPane4.setViewportView(jTree_Evenement);

        pnl_info_evenement.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pnl_info_evenementLayout = new javax.swing.GroupLayout(pnl_info_evenement);
        pnl_info_evenement.setLayout(pnl_info_evenementLayout);
        pnl_info_evenementLayout.setHorizontalGroup(
            pnl_info_evenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        pnl_info_evenementLayout.setVerticalGroup(
            pnl_info_evenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_evenementLayout = new javax.swing.GroupLayout(pnl_evenement);
        pnl_evenement.setLayout(pnl_evenementLayout);
        pnl_evenementLayout.setHorizontalGroup(
            pnl_evenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_evenementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_info_evenement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_evenementLayout.setVerticalGroup(
            pnl_evenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_evenementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_evenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(pnl_info_evenement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_mots_cles.addTab("Evenement", pnl_evenement);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        pnl_mots_cles.addTab("Mots-Clés", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_mots_cles)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnl_mots_cles)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(616, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*PARTIE THEME & SOUS-THEME-----------------------------------------------------------------------------------------------------------------------------------------------------*/
    private DefaultComboBoxModel initThemeModelComboBox() {
        return new DefaultComboBoxModel(initThemeVector());
    }

    private Vector initThemeVector() {
        Vector v = new Vector();
        for (Theme leTheme : this.lib.getLesThemes()) {
            v.add(leTheme);
        }
        Collections.sort(v);
        return v;
    }

    private DefaultTreeModel initThemesTreeModel() {
        return new DefaultTreeModel(initThemesTree());
    }

    private DefaultMutableTreeNode initThemesTree() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Mes Themes");

        DefaultMutableTreeNode tnTheme = null;
        DefaultMutableTreeNode tnSousTheme = null;

        Collections.sort(this.lib.getLesThemes());
        for (Theme unTheme : this.lib.getLesThemes()) {
            tnTheme = new DefaultMutableTreeNode(unTheme);
            root.add(tnTheme);
            List<Sous_theme> sesSousThemes = unTheme.getLeSous_themes();
            if (sesSousThemes != null) {
                Collections.sort(sesSousThemes);
                for (Sous_theme unSousTheme : sesSousThemes) {
                    tnTheme.add(tnSousTheme = new DefaultMutableTreeNode(unSousTheme));
                }
            }
        }
        System.out.println("Done!");

        return root;
    }

    private void btn_theme_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_theme_modifierActionPerformed
        // TODO add your handling code here:
        if (this.rb_sous_theme.isSelected()) {
            Sous_theme unSousTheme = new Sous_theme(Integer.valueOf(this.lbl_theme_id.getText()), ((Theme) this.cb_theme.getSelectedItem()), this.tf_theme_libelle.getText());
            lib.modifierSous_theme(unSousTheme);
        } else {
            Theme unTheme = new Theme(this.tf_theme_libelle.getText());
            lib.modifierTheme(unTheme);
        }
        this.lib.load();
        jTree_theme.setModel(this.initThemesTreeModel());
        cb_theme.setModel(this.initThemeModelComboBox());
    }//GEN-LAST:event_btn_theme_modifierActionPerformed

    private void btn_theme_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_theme_ajouterActionPerformed
        // TODO add your handling code here:
        if (this.rb_sous_theme.isSelected()) {
            Sous_theme unSousTheme = new Sous_theme(this.tf_theme_libelle.getText(), ((Theme) this.cb_theme.getSelectedItem()));
            lib.AjouterSous_theme(unSousTheme);
        } else {
            Theme unTheme = new Theme(this.tf_theme_libelle.getText());
            lib.AjouterTheme(unTheme);
        }
        this.lib.load();
        jTree_theme.setModel(this.initThemesTreeModel());
        cb_theme.setModel(this.initThemeModelComboBox());
    }//GEN-LAST:event_btn_theme_ajouterActionPerformed

    private void rb_sous_themeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_sous_themeItemStateChanged
        // TODO add your handling code here:
        this.pnl_cb_theme.setVisible(true);
    }//GEN-LAST:event_rb_sous_themeItemStateChanged

    private void rb_themeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_themeItemStateChanged
        // TODO add your handling code here:
        this.pnl_cb_theme.setVisible(false);
    }//GEN-LAST:event_rb_themeItemStateChanged

    private void btn_theme_afficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_theme_afficherActionPerformed
        // TODO add your handling code here:
        if (jTree_theme.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(jTree_Evenement, "Vous devez selectionner un theme ou un sous-theme!");
        } else {
            DefaultMutableTreeNode tn = (DefaultMutableTreeNode) jTree_theme.getLastSelectedPathComponent();
            if (tn.getUserObject() instanceof Sous_theme) {
                Sous_theme a = (Sous_theme) tn.getUserObject();
                this.rb_sous_theme.setSelected(true);
                this.lbl_theme_id.setText("" + a.getId_sous_theme());
                this.tf_theme_libelle.setText(a.getLibelle());
                this.cb_theme.setSelectedItem(a.getTheme());
            } else if (tn.getUserObject() instanceof Theme) {
                Theme a = (Theme) tn.getUserObject();
                this.rb_theme.setSelected(true);
                this.lbl_theme_id.setText("" + a.getId_theme());
                this.tf_theme_libelle.setText(a.getLibelle());
            } else {
                JOptionPane.showMessageDialog(jTree_Evenement, "Vous devez selectionner un theme ou un sous-theme!");
            }
        }

    }//GEN-LAST:event_btn_theme_afficherActionPerformed
    /*FIN THEME SOUS-THEMES  -----------------------------------------------------------------------------------------------------------------------------------------------------*/

    /*PARTIE AUTEURS -------------------------------------------------------------------------------------------------------------------------------------------------------------*/
    private void btn_auteur_afficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auteur_afficherActionPerformed
        // TODO add your handling code here:
        if (jTree_auteur.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(jTree_Evenement, "Vous devez selectionner un auteur!");
        } else {
            DefaultMutableTreeNode tn = (DefaultMutableTreeNode) jTree_auteur.getLastSelectedPathComponent();
            if (tn.getUserObject() instanceof Auteur) {
                Auteur a = (Auteur) tn.getUserObject();
                this.lbl_auteur_id.setText("" + a.getId_auteur());
                this.tf_auteur_nom.setText(a.getNom());
                this.tf_auteur_prenom.setText(a.getPrenom());
                this.tf_auteur_naissance.setText(a.getDate_de_naissance());
                this.tf_auteur_deces.setText(a.getDate_de_deces());
            } else {
                JOptionPane.showMessageDialog(jTree_Evenement, "Vous devez selectionner un auteur!");
            }

        }
    }//GEN-LAST:event_btn_auteur_afficherActionPerformed

    private void btn_auteur_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auteur_ajouterActionPerformed
        // TODO add your handling code here:
        Auteur unAuteur = new Auteur(this.tf_auteur_nom.getText(), this.tf_auteur_prenom.getText(), this.tf_auteur_naissance.getText(), this.tf_auteur_deces.getText());
        lib.AjouterAuteur(unAuteur);
        this.lib.load();
        jTree_auteur.setModel(this.initAuteursTreeModel());
        resetFieldsAuteur();
    }//GEN-LAST:event_btn_auteur_ajouterActionPerformed

    private void btn_auteur_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auteur_modifierActionPerformed
        // TODO add your handling code here:
        Auteur unAuteur = new Auteur(Integer.valueOf(this.lbl_auteur_id.getText()), this.tf_auteur_nom.getText(), this.tf_auteur_prenom.getText(), this.tf_auteur_naissance.getText(), this.tf_auteur_deces.getText());
        lib.modifierAuteur(unAuteur);
        this.lib.load();
        jTree_auteur.setModel(this.initAuteursTreeModel());
        resetFieldsAuteur();
    }//GEN-LAST:event_btn_auteur_modifierActionPerformed

    private void btn_auteurs_info_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auteurs_info_resetActionPerformed
        // TODO add your handling code here:
        resetFieldsAuteur();
    }//GEN-LAST:event_btn_auteurs_info_resetActionPerformed

    private void btn_auteur_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auteur_rechercheActionPerformed
        // TODO add your handling code here:
        this.lib.loadAuteur(this.tf_auteurs_recherche.getText());
        jTree_auteur.setModel(this.initAuteursTreeModel());
        resetFieldsAuteur();
    }//GEN-LAST:event_btn_auteur_rechercheActionPerformed

    private void btn_theme_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_theme_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_theme_rechercheActionPerformed

    private DefaultTreeModel initAuteursTreeModel() {
        return new DefaultTreeModel(initAuteursTree());
    }

    private DefaultMutableTreeNode initAuteursTree() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Mes Auteurs");

        DefaultMutableTreeNode tnAuteur = null;
        DefaultMutableTreeNode tnOuvrage = null;

        Collections.sort(this.lib.getLesAuteurs());
        for (Auteur unAuteur : this.lib.getLesAuteurs()) {
            tnAuteur = new DefaultMutableTreeNode(unAuteur);
            root.add(tnAuteur);
            List<Ouvrage> sesOuvrages = unAuteur.getLesOuvrages();
            if (sesOuvrages != null) {
                Collections.sort(sesOuvrages);
                for (Ouvrage unOuvrage : sesOuvrages) {
                    tnAuteur.add(tnOuvrage = new DefaultMutableTreeNode(unOuvrage));
                }
            }
        }
        System.out.println("Done!");

        return root;
    }

    private void resetFieldsAuteur() {
        this.tf_themes_recherche.setText("");
        this.lbl_auteur_id.setText("");
        this.tf_auteur_nom.setText("");
        this.tf_auteur_prenom.setText("");
        this.tf_auteur_naissance.setText("");
        this.tf_auteur_deces.setText("");
    }

    /*FIN AUTEURS ----------------------------------------------------------------------------------------------------------------------------------------------------------------*/
    /*PARTIE EDITEUR -------------------------------------------------------------------------------------------------------------------------------------------------------------*/
    private DefaultTreeModel initEditeursTreeModel() {
        return new DefaultTreeModel(initEditeursTree());
    }

    private DefaultMutableTreeNode initEditeursTree() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Mes Editeurs");

        DefaultMutableTreeNode tnEditeur = null;
        DefaultMutableTreeNode tnOuvrage = null;

        Collections.sort(this.lib.getLesEditeurs());
        for (Editeur unEditeur : this.lib.getLesEditeurs()) {
            tnEditeur = new DefaultMutableTreeNode(unEditeur);
            root.add(tnEditeur);
            List<Ouvrage> sesOuvrages = unEditeur.getLesOuvrages();
            if (sesOuvrages != null) {
                Collections.sort(sesOuvrages);
                for (Ouvrage unOuvrage : sesOuvrages) {
                    tnEditeur.add(tnOuvrage = new DefaultMutableTreeNode(unOuvrage));
                }
            }
        }
        System.out.println("Done!");

        return root;
    }
    /*FIN EDITEUR ----------------------------------------------------------------------------------------------------------------------------------------------------------------*/

    /*PARTIE EVENEMENT -------------------------------------------------------------------------------------------------------------------------------------------------------------*/
    private DefaultTreeModel initEvenementsTreeModel() {
        return new DefaultTreeModel(initEvenementsTree());
    }

    private DefaultMutableTreeNode initEvenementsTree() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Mes Editeurs");

        DefaultMutableTreeNode tnEvenement = null;
        DefaultMutableTreeNode tnOuvrage = null;

        Collections.sort(this.lib.getLesEvenements());
        for (Evenement unEvenement : this.lib.getLesEvenements()) {
            tnEvenement = new DefaultMutableTreeNode(unEvenement);
            root.add(tnEvenement);
            List<Ouvrage> sesOuvrages = unEvenement.getLesOuvrages();
            if (sesOuvrages != null) {
                Collections.sort(sesOuvrages);
                for (Ouvrage unOuvrage : sesOuvrages) {
                    tnEvenement.add(tnOuvrage = new DefaultMutableTreeNode(unOuvrage));
                }
            }
        }
        System.out.println("Done!");

        return root;
    }
    /*FIN EVENEMENT ----------------------------------------------------------------------------------------------------------------------------------------------------------------*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OuvrageSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OuvrageSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OuvrageSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OuvrageSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OuvrageSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_auteur_afficher;
    private javax.swing.JButton btn_auteur_ajouter;
    private javax.swing.JButton btn_auteur_modifier;
    private javax.swing.JButton btn_auteur_recherche;
    private javax.swing.JButton btn_auteurs_info_reset;
    private javax.swing.JButton btn_theme_afficher;
    private javax.swing.JButton btn_theme_ajouter;
    private javax.swing.JButton btn_theme_modifier;
    private javax.swing.JButton btn_theme_recherche;
    private javax.swing.ButtonGroup btngrp_theme_sous_theme;
    private javax.swing.JComboBox cb_theme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTree_Evenement;
    private javax.swing.JTree jTree_auteur;
    private javax.swing.JTree jTree_editeurs;
    private javax.swing.JTree jTree_theme;
    private javax.swing.JLabel lbl_auteur_deces_libelle;
    private javax.swing.JLabel lbl_auteur_id;
    private javax.swing.JLabel lbl_auteur_id_libelle;
    private javax.swing.JLabel lbl_auteur_naissance_libelle;
    private javax.swing.JLabel lbl_auteur_nom_libelle;
    private javax.swing.JLabel lbl_auteur_prenom_libelle;
    private javax.swing.JLabel lbl_auteur_rechercher;
    private javax.swing.JLabel lbl_cb_theme;
    private javax.swing.JLabel lbl_libelle_theme_libelle;
    private javax.swing.JLabel lbl_theme_id;
    private javax.swing.JLabel lbl_theme_id_libelle;
    private javax.swing.JLabel lbl_theme_rechercher;
    private javax.swing.JPanel pnl_auteur_rechercher;
    private javax.swing.JPanel pnl_auteur_rechercher1;
    private javax.swing.JPanel pnl_auteurs;
    private javax.swing.JPanel pnl_cb_theme;
    private javax.swing.JPanel pnl_editeurs;
    private javax.swing.JPanel pnl_evenement;
    private javax.swing.JPanel pnl_info_editeur;
    private javax.swing.JPanel pnl_info_evenement;
    private javax.swing.JPanel pnl_info_theme;
    private javax.swing.JPanel pnl_ouvrages;
    private javax.swing.JPanel pnl_themes;
    private javax.swing.JRadioButton rb_sous_theme;
    private javax.swing.JRadioButton rb_theme;
    private javax.swing.JTextField tf_auteur_deces;
    private javax.swing.JTextField tf_auteur_naissance;
    private javax.swing.JTextField tf_auteur_nom;
    private javax.swing.JTextField tf_auteur_prenom;
    private javax.swing.JTextField tf_auteurs_recherche;
    private javax.swing.JTextField tf_theme_libelle;
    private javax.swing.JTextField tf_themes_recherche;
    // End of variables declaration//GEN-END:variables
}
