/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.*;
import data.*;

/**
 *
 * @author cda402
 */
public class OuvrageSwing extends javax.swing.JFrame {

    /**
     * Creates new form Ouvrage
     */
    
    private Librairie lib = new Librairie();
    private DAOtheme dao = new DAOtheme();
    
    public OuvrageSwing() {
        initComponents();
        dao.open();
        lib.setLesThemes(dao.select());
        dao.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane tbp_gestion = new javax.swing.JTabbedPane();
        pnl_ouvrages = new javax.swing.JPanel();
        pnl_themes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_themes = new javax.swing.JTable();
        pnl_sous_themes = new javax.swing.JPanel();
        pnl_auteurs = new javax.swing.JPanel();
        pnl_editeurs = new javax.swing.JPanel();
        pnl_evenement = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnl_ouvragesLayout = new javax.swing.GroupLayout(pnl_ouvrages);
        pnl_ouvrages.setLayout(pnl_ouvragesLayout);
        pnl_ouvragesLayout.setHorizontalGroup(
            pnl_ouvragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        pnl_ouvragesLayout.setVerticalGroup(
            pnl_ouvragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        tbp_gestion.addTab("Ouvrages", pnl_ouvrages);

        tbl_themes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_themes);

        javax.swing.GroupLayout pnl_themesLayout = new javax.swing.GroupLayout(pnl_themes);
        pnl_themes.setLayout(pnl_themesLayout);
        pnl_themesLayout.setHorizontalGroup(
            pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        pnl_themesLayout.setVerticalGroup(
            pnl_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_themesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 163, Short.MAX_VALUE))
        );

        tbp_gestion.addTab("Thèmes", pnl_themes);

        javax.swing.GroupLayout pnl_sous_themesLayout = new javax.swing.GroupLayout(pnl_sous_themes);
        pnl_sous_themes.setLayout(pnl_sous_themesLayout);
        pnl_sous_themesLayout.setHorizontalGroup(
            pnl_sous_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        pnl_sous_themesLayout.setVerticalGroup(
            pnl_sous_themesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        tbp_gestion.addTab("Sous-thèmes", pnl_sous_themes);

        javax.swing.GroupLayout pnl_auteursLayout = new javax.swing.GroupLayout(pnl_auteurs);
        pnl_auteurs.setLayout(pnl_auteursLayout);
        pnl_auteursLayout.setHorizontalGroup(
            pnl_auteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        pnl_auteursLayout.setVerticalGroup(
            pnl_auteursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        tbp_gestion.addTab("Auteurs", pnl_auteurs);

        javax.swing.GroupLayout pnl_editeursLayout = new javax.swing.GroupLayout(pnl_editeurs);
        pnl_editeurs.setLayout(pnl_editeursLayout);
        pnl_editeursLayout.setHorizontalGroup(
            pnl_editeursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        pnl_editeursLayout.setVerticalGroup(
            pnl_editeursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        tbp_gestion.addTab("Editeurs", pnl_editeurs);

        javax.swing.GroupLayout pnl_evenementLayout = new javax.swing.GroupLayout(pnl_evenement);
        pnl_evenement.setLayout(pnl_evenementLayout);
        pnl_evenementLayout.setHorizontalGroup(
            pnl_evenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        pnl_evenementLayout.setVerticalGroup(
            pnl_evenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        tbp_gestion.addTab("Evenement", pnl_evenement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbp_gestion)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tbp_gestion)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(616, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OuvrageSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OuvrageSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OuvrageSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OuvrageSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OuvrageSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_auteurs;
    private javax.swing.JPanel pnl_editeurs;
    private javax.swing.JPanel pnl_evenement;
    private javax.swing.JPanel pnl_ouvrages;
    private javax.swing.JPanel pnl_sous_themes;
    private javax.swing.JPanel pnl_themes;
    private javax.swing.JTable tbl_themes;
    // End of variables declaration//GEN-END:variables
}
